services:
  coursesignal_db:
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: "test"
  coursesignal_server:
    volumes:
      - ../frontend:/usr/src/coursesignal
    command: ["npx", "nodemon", "--legacy-watch", "CourseSignal.js"]
