services:
  coursesignal_db:
    build: ../database
    volumes:
      - ../database/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${COURSESIGNAL_DB_PASSWORD}"
      MARIADB_DATABASE: "CourseSignal"
    labels:
      container_name: coursesignal_db
  coursesignal_server:
    build: ../frontend
    ports:
      - "4000:4000"
    labels:
      container_name: coursesignal_server
